# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  workflow_dispatch:

jobs:
  pytest:
    name: Execute Pytest
    runs-on: ubuntu-latest
    steps:
      -
        name: Run All Pytests
        run: pytest